apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: system
  labels:
    app.kubernetes.io/name: virt-template
    app.kubernetes.io/managed-by: kustomize
    kubevirt.io: virt-template-api-service
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - name: http-api
      port: 443
      protocol: TCP
      targetPort: http-api
  selector:
    control-plane: apiserver
    app.kubernetes.io/name: virt-template
