apiVersion: template.kubevirt.io/v1beta1
kind: VirtualMachineTemplateRequest
metadata:
  name: virtualmachinetemplaterequest-sample
  labels:
    app.kubernetes.io/name: virt-template
    app.kubernetes.io/managed-by: kustomize
    kubevirt.io: virtualmachinetemplaterequest-sample
spec:
  templateName: my-template
  ttlSecondsAfterFinished: 3600
  virtualMachineRef:
    namespace: my-vm-namespace
    name: my-vm
  # Optional: labels to apply to the created VirtualMachineTemplate
  templateLabels:
    example.com/os: linux
    example.com/workload: server
